### ISSUE TITLE
画像を変更してください

### ISSUE THREAD

**Issue by gyamada-ca** [marnicat/siguma#6]
画像を明るい色に変更して、○○を付け加えてください

**Comment by marnicat** [comment]
@gyamada-cz 
ステージングに上げたので確認してください。
http://wwww

**Comment by gyamada-ca** [comment]
画像はこのサイズであってます？

**Comment by marnicat** [comment]
あってます。

**Comment by gyamada-ca** [comment]
👍

**Comment by gyamada-ca** [comment]
![octocat](https://cloud.githubusercontent.com/assets/26395911/24360162/7ca5c5f8-1341-11e7-84c7-834fbb078b99.png)
こんな感じにしてください。

**Comment by marnicat** [comment]
👍
